### ISSUE TITLE
[Not A bug] This is communication attempt

### ISSUE THREAD

**Issue by MikeYuanMY** [Oaphi/MenuApp#66]
Hi Oleg,

This is Mike from Keela

I am terribly sorry for reaching out here on GitHub. I couldn't reach you via previous email.

We need some assistance with our Cardin app.

would you be able assist us?

Please reach out to me at mike.yuan@keela.com or mike.yuan84@gmail.com.

Thank you!

**Comment by Oaphi** [comment]
Hi Mike, sure - I'll close the issue for now, and will follow up via email

**Comment by MikeYuanMY** [comment]
oops left the wrong email, you can also reach me at yuan.mike84@gmail.com
